[theme]
base = "light"
primaryColor = "#635BFF"          # Stripe Blurple
backgroundColor = "#F6F9FC"       # Off-white
secondaryBackgroundColor = "#FFFFFF" # panels/ sidebar
textColor = "#1A1F36"             # Slate
font = "sans serif"